# This file was generated by GoReleaser. DO NOT EDIT.
cask "orriven" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "5019103ca8a9d6c7f6ba56708d38207f3f98609202d99d08992868e9ff8d1cdd"
      url "https://github.com/orriven/cli/releases/download/v#{version}/orriven_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "385120fe06cf599f19d3b0add5fbdadf96b681f0ebcbd8bf01ba5c5a3c09bf1b"
      url "https://github.com/orriven/cli/releases/download/v#{version}/orriven_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "2d5c9a24381652214148040ce0bed99f4d075409bc0f1ee8c5b6f8d2b94a3d86"
      url "https://github.com/orriven/cli/releases/download/v#{version}/orriven_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "a8fb00e85201e8745dd9be06b0132ccff8e79cc650f242dc8bc062fd1adcddad"
      url "https://github.com/orriven/cli/releases/download/v#{version}/orriven_#{version}_linux_amd64.tar.gz"
    end
  end

  name "orriven"
  desc "The orriven command-line tool"
  homepage "https://orriven.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "orriven"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/orriven"]
    end
  end

  # No zap stanza required
end
