# This file was generated by GoReleaser. DO NOT EDIT.
cask "orriven" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "52313d98ab3409d69f4f2b49fad41cb9d1c0487457214757a97d81be133cc371"
      url "https://github.com/orriven/cli/releases/download/v#{version}/orriven_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d0bedb01633cba52b53841145dee7bd336a5f3ff0e60be58370110f006373d32"
      url "https://github.com/orriven/cli/releases/download/v#{version}/orriven_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "74c087db1a44717f31c9b4dbdfdcfd7551bffbb6cebacfa845a10d39e2852dde"
      url "https://github.com/orriven/cli/releases/download/v#{version}/orriven_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "16d64b57dd986b7f648957a15c6636ca51cceeed489cc588e5ea1641ede79cfb"
      url "https://github.com/orriven/cli/releases/download/v#{version}/orriven_#{version}_linux_amd64.tar.gz"
    end
  end

  name "orriven"
  desc "The orriven command-line tool"
  homepage "https://orriven.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "orriven"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/orriven"]
    end
  end

  # No zap stanza required
end
